<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUKvmqKh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUKvmqKh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUKvmqKh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUKvmqKh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUKvmqKh\App_KernelDevDebugContainer([
    'container.build_hash' => 'UKvmqKh',
    'container.build_id' => '49e16e80',
    'container.build_time' => 1597920618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUKvmqKh');
